### ISSUE TITLE
[App crash]

### ISSUE THREAD

**Issue by RE3CON** [BobbyESP/Metadator#6]
java.lang.OutOfMemoryError: Failed to allocate a 96 byte allocation with 1612576 free bytes and 1574KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.String.fastSubstring(Native Method)
	at java.lang.String.substring(String.java:2499)
	at w4.h.a(SourceFile:311)
	at w4.e.n(SourceFile:13)
	at a6.a.l(SourceFile:9)
	at w6.F.run(SourceFile:113)
	at P4.s.run(SourceFile:232)
	at D6.k.run(SourceFile:3)
	at D6.a.run(SourceFile:96)
	Suppressed: B6.f: [C{Cancelling}@74d31b5, Dispatchers.IO]
Android 14

**Comment by BobbyESP** [comment]
Can I ask when this happened, in which context?

**Comment by BobbyESP** [comment]
Thanks mate for reaching out and sorry for the delay. I will take a look to this but I need a way to reproduce the error. If you could provide some extra information I would be very grateful.

**Comment by BobbyESP** [comment]
Since there is no more information, I'll be closing this issue. If at some point this occurs another time, please, contact us back
