### ISSUE TITLE
[App crash]

### ISSUE THREAD

**Issue by RE3CON** [BobbyESP/Metadator#7]
App version: com.bobbyesp.metadator 1.0.0-beta.7 (107)
Android version: Android 14 (API 34)
Device: samsung SM-X210
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]

java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 1300080 free bytes and 1269KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at s0.F.a(SourceFile:3)
	at L0.z0.n(SourceFile:52)
	at L0.z0.i(SourceFile:23)
	at K0.e0.b1(SourceFile:74)
	at K0.e0.h(SourceFile:79)
	at I0.a0.f(SourceFile:31)
	at R0.p.f(SourceFile:19)
	at L0.K.S(SourceFile:56)
	at L0.K.r(SourceFile:60)
	at L0.K.S(SourceFile:31)
	at L0.K.r(SourceFile:60)
	at L0.K.S(SourceFile:31)
	at L0.K.r(SourceFile:60)
	at L0.K.r(SourceFile:84)
	at L0.K.S(SourceFile:31)
	at L0.K.R(SourceFile:43)
	at L0.K.u(SourceFile:39)
	at L0.K.p(SourceFile:60)
	at L0.K.J(SourceFile:12)
	at L0.K.K(SourceFile:7)
	at L0.K.O(SourceFile:148)
	at L0.K.m(SourceFile:154)
	at L0.G.n(SourceFile:12)
	at a6.a.l(SourceFile:9)
	at w6.F.run(SourceFile:113)
	at L0.d0.H(SourceFile:24)
	at L0.c0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: B6.f: [L0.E0@c04fc6f, Z.h@fe37d7c, C{Cancelling}@e006605, d0@21f265a]

**Comment by BobbyESP** [comment]
Related to #6
